spring.application.name=tvmaze

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://g13_db_user:Conexion123@personal.qwhlwbv.mongodb.net/tv_maze?appName=Personal
spring.mongodb.auto-index-creation=true

